### PR TITLE
Fix dependencies to work with jupyterlab 1.0.0

### LINKED ISSUE #44: Events not working with jupyterlab 1.0.0
Thanks for the really useful package and clean API.
I just tried to run the example in `doc/Widget DOM Events.ipynb` and it works fine on a jupyter notebook but does not work with jupyterlab 1.0.0.  No events are captured on jupyterlab.  This is with ipyevents 0.5.0 from conda-forge and Python 3.7.3.  Thanks.

### PR DESCRIPTION
**Pull request by prabhuramachandran**
As discussed in issue #44, this fixes #44.

### CODE REVIEW

**Comment by mwcraig** [comment]
Thanks @prabhuramachandran, will release today

**Comment by prabhuramachandran** [comment]
Great!  Thank you!

**Comment by mwcraig** [comment]
Thanks again for the fix; getting the release out took a few more days than anticipated but the silver lining is that you no longer need to install the jupyter labextension as a separate step. The release 0.6.1 contains your fix and the simplified installation.

**Comment by prabhuramachandran** [comment]
Thank you, that sounds great.  I wish there were an easy way to install it for jupyter also, does this release also not require the `$ jupyter nbextension install --py --symlink --sys-prefix ipyevents` stuff when installing via `pip`.

**Comment by mwcraig** [comment]
It should also automatically install the nbextension too, though that only works for notebook versions newer than 5.2

Matt

**Pull request merged**
