### PR TITLE
Bump versions for JupyterLab 2.0 support

### LINKED ISSUE #52: Support for JupyterLab 2.0
JupyterLab has had a major version release (2.0) and unfortunately, it broke a lot of extensions, including ipyevents.

I think all it will take is to follow the instructions in the [extension migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#extension-migration) to make it work again.

### PR DESCRIPTION
**Pull request by itssimon**
Fixes #52

### CODE REVIEW

**Comment by mwcraig** [comment]
@itssimon -- can you give this a try? It updates the plugin to avoid phosphor/lumino. I've tested locally but if you could confirm that it works for you with jlab 2 that would be great.

**Comment by pkgw** [comment]
Umm, this doesn't seem to be working for me on JLab 2.0, but I'm very unclear as to whether *anything* is working right so I don't know if that's necessarily a problem with this pull request.

A sample notebook from ipywidgets works, once I install the necessary development versions of all the packages, but in the "Widget DOM Events" notebook the widgets do not seem to be receiving any events. If I type a "d" on the "Click me" widget, a cell is deleted, etc.

**Comment by pkgw** [comment]
If I try a similar testing plan with JLab 1.2.7, ipyevents *is* working, so that's something. Next I'll try to document my setup/test steps for concreteness.

**Comment by pkgw** [comment]
Here's what I am trying that is not leading to eventy widgets for me:

```
git clone -o itssimon git@github.com:itssimon/ipyevents.git
cd ipyevents
git switch jupyterlab-2.0
conda create -n tmp_jl2x_py38 python=3.8 'jupyterlab >=2.0'
conda activate tmp_jl2x_py38
# --
pip install --pre ipywidgets
jupyter nbextension install --py --symlink --sys-prefix widgetsnbextension
jupyter nbextension enable widgetsnbextension --py --sys-prefix
# --
jupyter labextension install @jupyter-widgets/jupyterlab-manager@3.0.0-alpha.0
# --
pip install -e .
jupyter nbextension install --py --symlink --sys-prefix ipyevents
jupyter nbextension enable --py --sys-prefix ipyevents
npm install
npm run build
jupyter labextension install
# --
jupyter lab
```

**Comment by mwcraig** [comment]
I'll take a look later tonight. I think you should be using `@jupyter-widgets/jupyterlab-manager@2` though, not v3-alpha based on this: https://www.npmjs.com/package/@jupyter-widgets/jupyterlab-manager

**Comment by pkgw** [comment]
@mwcraig Ah, looks like you're right. The ipywidgets `--pre` version may also be incorrect too, then.

**Comment by mwcraig** [comment]
This sequence is working for me:

```
conda create -n tmp_jl2x_py38 python=3.8 'jupyterlab >=2.0'
conda activate tmp_jl2x_py38
conda install ipywidgets
conda install nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
git clean -fxd
pip install -e .
jupyter labextension list
npm install
npm run build
jupyter labextension install
cd doc
jupyter lab
```

**Comment by mwcraig** [comment]
Auto-install of the lab extension isn't working at the moment but I'm inclined to release anyway.

**Comment by mwcraig** [comment]
I've asked a question on gitter about auto-installing the extension. Whether I get an answer or not I'll go ahead and release Thursday morning. If I can get autoinstall working that would be nice.

**Comment by mwcraig** [comment]
Merging, turns out auto-install still works for a non-dev install. Release shortly.

**Comment by mwcraig** [comment]
The release is done, thanks @itssimon and @pkgw! My apologies @itssimon for not getting your name in the contributor list before the release; it is there now!

conda-forge package might not be ready until the morning depend on how fast the bot is.

**Pull request merged**
