### PR TITLE
Update for JupyterLab 3

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
I'll switch from Travis to Github actions if that is fine with you (TravisCI changed their free plan and you might be out of free credits very soon)

**Comment by mwcraig** [comment]
@martinRenou -- thanks, this seems to be working. One question before I merge: will this still work with jlab 2, or will it only be jlab3 from now on?

**Comment by martinRenou** [comment]
I think it should still work for JupyterLab 2 (if the labextension is installed manually). But we should maybe give it a try

**Comment by mwcraig** [comment]
Trying it out locally....

**Comment by mwcraig** [comment]
It worked locally with jlab2. 

When I tried locally with jlab3 in a conda environment I still had to install `nodejs` for the install to succeed. Is that normal?

**Comment by mwcraig** [comment]
Thanks again, @martinRenou, this works locally and here so I'm merging it.

**Comment by martinRenou** [comment]
> When I tried locally with jlab3 in a conda environment I still had to install nodejs for the install to succeed. Is that normal?

Yes, at least for the dev installation. But once you publish the extension on PyPi it should ship the JavaScript build assets so users don't need nodejs :)

**Pull request merged**
