### PR TITLE
Add throttle/debounce

### LINKED ISSUE #54: Throttling?
Is it possible to throttle the message queue? Any tips on how to do this?

I tried overriding the `on_dom_event` (the function being passed) with the throttler in https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html#Throttling but it doesn't work here?

See https://github.com/Kitware/ipyvtk-simple/pull/8

### PR DESCRIPTION
**Pull request by mwcraig**
Closes #54 by adding throttle/debounce. 

- [ ] Write a bit of documentation for this

Brief useage:

```python
e = Event()
# Choose method of decreasing event rate, either 'throttle' or 'debounce' or None.
e.throttle_or_debounce = 'throttle'

# Set the throttle or debounce time in millseconds (must be an non-negative integer)
e.wait = 100

# If you set wait without setting throttle/debounce first then throttle is used.

# Set the wait back to zero to turn off throttle/debounce
e.wait = 0
```

### CODE REVIEW

**Comment by mwcraig** [comment]
@banesullivan -- I don't usually get around to adding code this quick but your suggestion came just before SciPy 2020, so this was a good excuse to do some work on the package. Hoping to add some additional documentation and automate the testing before merging.

Let me know if you have time to give this a try.

**Comment by banesullivan** [comment]
Tried, but I can't get the `nbextension` to enable with a developer install 😞

This stuff is always a pain for me

**Comment by mwcraig** [comment]
Are you using classic notebook or lab? 

If the dev install is a hassle, though, I can merge this later and do a beta release on pypi for you to install.

**Comment by banesullivan** [comment]
I'm trying with just classic notebook to keep it simple

**Comment by mwcraig** [comment]
Odd, that case should work with `pip install -e .`. What do you get from `jupyter nbextension list`?

**Comment by banesullivan** [comment]
I created a fresh virtual environment, pip installed jupyter, followed the dev install instructions for ipyevents, then:

```bash
$ jupyter nbextension list
Known nbextensions:
  config dir: /Users/bane/.jupyter/nbconfig
    notebook section
      ipyevents/extension disabled
  config dir: /Users/bane/anaconda3/envs/ipye/etc/jupyter/nbconfig
    notebook section
      ipycanvas/extension  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      ipyevents/extension  enabled
      - Validating: problems found:
        - require?  X ipyevents/extension
```

I'm just having trouble getting the extension to work... I'm not too sure how to debug these issues and I totally don't want to eat up your time with it either.

I may try this again in a Docker container to remove any complications from my local set up and hopefully that'll work

**Comment by mwcraig** [comment]
This looks like an issue with the ipyevents nbextension 😬. Investigating locally...

**Comment by mwcraig** [comment]
@banesullivan -- ok you should be able to try it now. I had accidentally the extension file 🤦‍♂️

**Comment by banesullivan** [comment]
Woohoo! It seems to be working great!!

**Comment by mwcraig** [comment]
Excellent, I'll work on a bit of documentation later today then merge and release

**Pull request merged**
